name: Build OpenWrt ipk

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-ipk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3

      - name: Download OpenWrt SDK
        run: |
          export OWRT_SDK_URL="https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          wget "$OWRT_SDK_URL" -O sdk.tar.xz
          tar -xf sdk.tar.xz
          SDK_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-*")
          echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV

      - name: Copy packages to SDK
        run: |
          source $GITHUB_ENV
          mkdir -p $SDK_DIR/package/luci-app-cloud-control
          cp -r luci-app-cloud-control/* $SDK_DIR/package/luci-app-cloud-control/
          mkdir -p $SDK_DIR/package/cloud-control
          cp -r cloud-control/* $SDK_DIR/package/cloud-control/

      - name: Update Feeds & Install Feeds
        run: |
          source $GITHUB_ENV
          cd $SDK_DIR
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate .config and defconfig
        run: |
          source $GITHUB_ENV
          cd $SDK_DIR
          echo "CONFIG_PACKAGE_cloud-control=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-cloud-control=y" >> .config
          make defconfig

      - name: Build cloud-control
        run: |
          source $GITHUB_ENV
          cd $SDK_DIR
          make package/cloud-control/compile V=s

      - name: Build luci-app-cloud-control
        run: |
          source $GITHUB_ENV
          cd $SDK_DIR
          make package/luci-app-cloud-control/compile V=s

      - name: Archive Built ipk
        if: success()
        run: |
          source $GITHUB_ENV
          mkdir -p ipk-out
          find $SDK_DIR/bin/ -name "*.ipk" -exec cp {} ipk-out/ \;

      - name: Upload ipk Artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-cloud-control-ipk
          path: ipk-out/
