name: Build OpenWrt IPK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x86_64
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64
          - name: bcm27xx_bcm2710
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/bcm27xx/bcm2710/openwrt-sdk-23.05.3-bcm27xx-bcm2710_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-bcm27xx-bcm2710_gcc-12.3.0_musl.Linux-x86_64
          - name: ipq40xx_generic
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/ipq40xx/generic/openwrt-sdk-23.05.3-ipq40xx-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-ipq40xx-generic_gcc-12.3.0_musl.Linux-x86_64
          - name: ipq806x_generic
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/ipq806x/generic/openwrt-sdk-23.05.3-ipq806x-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-ipq806x-generic_gcc-12.3.0_musl.Linux-x86_64
          - name: mediatek_filogic
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
          - name: rockchip_armv8
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/rockchip/armv8/openwrt-sdk-23.05.3-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64
          - name: ramips_mt76x8
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt76x8/openwrt-sdk-23.05.3-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-ramips-mt76x8_gcc-12.3.0_musl.Linux-x86_64
          - name: ramips_mt7621
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt7621/openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64
          - name: ath79_generic
            sdk_url: https://downloads.openwrt.org/releases/23.05.3/targets/ath79/generic/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
            sdk_dir: openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib git gettext libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget python3

      - name: Download and extract SDK
        run: |
          wget ${{ matrix.sdk_url }} -O sdk.tar.xz
          tar -xf sdk.tar.xz

      - name: Prepare package directory
        run: |
          mkdir -p ${{ matrix.sdk_dir }}/package/nikki
          rsync -a --exclude=.git ./ ${{ matrix.sdk_dir }}/package/nikki/

      - name: Update & install feeds
        run: |
          cd ${{ matrix.sdk_dir }}
          ./scripts/feeds update -a || true
          ./scripts/feeds install -a || true

      - name: Configure .config and defconfig
        run: |
          cd ${{ matrix.sdk_dir }}
          echo "CONFIG_PACKAGE_nikki=y" >> .config
          make defconfig

      - name: Build package
        run: |
          cd ${{ matrix.sdk_dir }}
          make package/nikki/compile V=s

      - name: Collect ipk
        run: |
          mkdir -p ipk
          find ${{ matrix.sdk_dir }}/bin/ -name "*.ipk" -exec cp {} ipk/ \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nikki-ipk-${{ matrix.name }}
          path: ipk/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/nikki-ipk-*/**/*.ipk
