name: Build cloud-control & luci-app-cloud-control (x86_64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip

      - name: Clone OpenWrt 24.10 for x86_64
        run: |
          git clone --depth=1 -b openwrt-24.10 https://github.com/openwrt/openwrt.git openwrt

      - name: Update feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Set build target to x86_64
        working-directory: openwrt
        run: |
          echo 'CONFIG_TARGET_x86=y' >> .config
          echo 'CONFIG_TARGET_x86_64=y' >> .config
          echo 'CONFIG_TARGET_x86_64_Generic=y' >> .config
          make defconfig

      - name: Copy cloud-control backend
        run: |
          mkdir -p openwrt/package/cloud-control
          cp -r cloud-control/* openwrt/package/cloud-control/

      - name: Copy luci-app-cloud-control frontend
        run: |
          mkdir -p openwrt/package/luci-app-cloud-control
          cp -r Makefile luasrc root openwrt/package/luci-app-cloud-control/

      - name: Compile packages
        working-directory: openwrt
        run: |
          make package/cloud-control/compile V=s -j$(nproc)
          make package/luci-app-cloud-control/compile V=s -j$(nproc)

      - name: Upload IPK packages
        uses: actions/upload-artifact@v4
        with:
          name: cloud-control-ipks
          path: |
            openwrt/bin/packages/x86_64/*/cloud-control_*.ipk
            openwrt/bin/packages/x86_64/*/luci-app-cloud-control_*.ipk
